# @package _global_

defaults:
  - override /hydra/launcher: submitit_slurm

hydra:
  launcher:
    account: ${paths.account}
    partition: gpu
    gpus_per_task: 1
    mem_gb: 60
    timeout_min: 180